### ISSUE TITLE
RuntimeError: input.size(-1) must be equal to input_size. Expected 28, got 31

### ISSUE THREAD

**Issue by xiaominy** [uoe-agents/LIAM#3]
Hi, i download your code and run then it made an error, i don't know where the '28' is, how can I solve this problem? Thanks!
the error msg is:

WARN: Could not seed environment <MultiAgentEnv instance>
WARN: Could not seed environment <MultiAgentEnv instance>
WARN: Could not seed environment <MultiAgentEnv instance>
WARN: Could not seed environment <MultiAgentEnv instance>
WARN: Could not seed environment <MultiAgentEnv instance>
WARN: Could not seed environment <MultiAgentEnv instance>
WARN: Could not seed environment <MultiAgentEnv instance>
WARN: Could not seed environment <MultiAgentEnv instance>
WARN: Could not seed environment <MultiAgentEnv instance>
WARN: Could not seed environment <MultiAgentEnv instance>
28
Number of updates that will be performed 160000
D:\projects\MADRL\LIAM-main\main.py:81: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ..\torch\csrc\utils\tensor_new.cpp:201.)
  agent_obs = torch.FloatTensor([o[1] for o in obs])
input_tensor shape torch.Size([10, 31])
x torch.Size([10, 31])
x torch.Size([1, 10, 31])
Traceback (most recent call last):
  File "run_tests.py", line 43, in <module>
    main(exec_params)
  File "D:\projects\MADRL\LIAM-main\main.py", line 98, in main
    actions, actions1, actions2, value, hidden = agent.act(agent_obs, actions, hidden)
  File "D:\projects\MADRL\LIAM-main\agent.py", line 28, in act
    embedding, hidden = self.compute_embedding(obs, action, hidden)
  File "D:\projects\MADRL\LIAM-main\agent.py", line 24, in compute_embedding
    embedding, hidden = self.encoder(input_tensor, hidden)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\projects\MADRL\LIAM-main\models.py", line 40, in forward
    h, hidden = self.lstm(x, hidden)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\rnn.py", line 689, in forward
    self.check_forward_args(input, hx, batch_sizes)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\rnn.py", line 632, in check_forward_args
    self.check_input(input, batch_sizes)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\rnn.py", line 205, in check_input
    raise RuntimeError(
RuntimeError: input.size(-1) must be equal to input_size. Expected 28, got 31

**Comment by sicsem** [comment]
also meet this problem
